stages:
  - build
  - test
  - push
  - deploy
  - monitor

variables:
  DOCKER_IMAGE: registry.gitlab.com/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME

before_script:
  - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token --password-stdin registry.gitlab.com

build:
  stage: build
  script:
    - docker build -t $DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA ./backend

test:
  stage: test
  script:
    - docker run --rm $DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA pytest tests/

push:
  stage: push
  script:
    - docker push $DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA

deploy:
  stage: deploy
  script:
    - kubectl apply -f .
    - kubectl apply -f ./k8s/ 
  only:
    - main

monitor:
  stage: monitor
  script:
    - kubectl apply -f .       
    - kubectl apply -f ./k8s/  

