services:   
  app:
    build: .
    container_name: sentiment_app
    image: hamzaazroul/sentiment-app:latest
    ports:
      - "8502:8501"
      - "8000:8000"  # <-- expose Prometheus metrics
    volumes:
      - .:/app
    depends_on:
      - prometheus
    networks:
      - sentiment-net
    restart: always

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
    - sentiment-net
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning
      - ./dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus
    networks:
      - sentiment-net
    restart: always

volumes:
  grafana-storage:

networks:
  sentiment-net:
    driver: bridge

  
