apiVersion: v1
kind: Service
metadata:
  name: sentiment-service
spec:
  selector:
    app: sentiment-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000 
      name: http
  type: NodePort
