apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sentiment-app-monitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: sentiment-app
  namespaceSelector:
    matchNames:
      - sentiment-app
  endpoints:
    - port: http
      interval: 10s
